import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "on-background": "#ffffff",
        "surface-variant": "#262627",
        "surface-dim": "#0e0e0f",
        "on-surface-variant": "#adaaab",
        "on-tertiary": "#400072",
        "secondary": "#34b5fa",
        "tertiary": "#c890ff",
        "on-tertiary-container": "#2e0055",
        "outline-variant": "#484849",
        "on-error": "#490013",
        "primary-fixed": "#ae8dff",
        "surface-container": "#1a191b",
        "on-surface": "#ffffff",
        "on-secondary": "#003047",
        "secondary-dim": "#17a8ec",
        "secondary-fixed": "#a4d8ff",
        "inverse-primary": "#6e3bd7",
        "surface": "#0e0e0f",
        "error": "#ff6e84",
        "primary-container": "#ae8dff",
        "secondary-container": "#006591",
        "primary-fixed-dim": "#a27cff",
        "surface-container-high": "#201f21",
        "on-primary-container": "#2b006e",
        "surface-bright": "#2c2c2d",
        "surface-container-highest": "#262627",
        "on-primary-fixed-variant": "#370086",
        "secondary-fixed-dim": "#81ccff",
        "tertiary-fixed": "#cd9bff",
        "surface-tint": "#ba9eff",
        "outline": "#767576",
        "background-alt": "#0e0e0f",
        "on-primary": "#39008c",
        "tertiary-dim": "#be83fa",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#00567c",
        "on-secondary-container": "#f3f8ff",
        "primary-dim": "#8455ef",
        "error-dim": "#d73357",
        "primary": "#ba9eff",
        "surface-container-low": "#131314",
        "tertiary-container": "#bc80f8",
        "tertiary-fixed-dim": "#c488ff",
        "inverse-on-surface": "#565556",
        "on-tertiary-fixed": "#270048",
        "on-tertiary-fixed-variant": "#53108c",
        "on-error-container": "#ffb2b9",
        "inverse-surface": "#fcf8f9",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed": "#003853"
      },
      fontFamily: {
        headline: ["var(--font-manrope)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
