import Razorpay from 'razorpay';
import crypto from 'crypto';
import config from '../../core/config/index.js';
import Transaction from './transaction.model.js';
import User from '../auth/auth.model.js';

// ─── Plan Config ────────────────────────────────────────────────────────────
// Amount in paise (INR × 100), downloads granted per plan
export const PLANS = {
  starter: {
    name: 'Starter',
    amount: 1900,        // ₹19
    currency: 'INR',
    downloads: 20,       // 20 downloads, valid 30 days
    validDays: 30,
    description: '20 Downloads · 30 Days · 320kbps',
  },
  pro_monthly: {
    name: 'Pro Monthly',
    amount: 9900,        // ₹99
    currency: 'INR',
    downloads: 300,      // 300/month fair use
    validDays: 30,
    description: '300 Downloads · 30 Days · Highest Quality',
  },
  pro_yearly: {
    name: 'Pro Yearly',
    amount: 79900,       // ₹799
    currency: 'INR',
    downloads: 3600,     // 300 × 12
    validDays: 365,
    description: '3600 Downloads · 365 Days · Priority Support',
  },
};

// ─── Razorpay Instance ───────────────────────────────────────────────────────
const getRazorpay = () => {
  if (!config.razorpay.keyId || !config.razorpay.keySecret) {
    throw new Error('Razorpay credentials are not configured.');
  }
  return new Razorpay({
    key_id: config.razorpay.keyId,
    key_secret: config.razorpay.keySecret,
  });
};

// ─── Service Methods ─────────────────────────────────────────────────────────

/**
 * Create a Razorpay order for a given plan
 * @param {string} userId
 * @param {string} planKey - 'starter' | 'pro_monthly' | 'pro_yearly'
 * @returns {Promise<{ orderId, amount, currency, plan }>}
 */
export const createOrder = async (userId, planKey) => {
  const plan = PLANS[planKey];
  if (!plan) {
    const error = new Error(`Invalid plan: ${planKey}`);
    error.statusCode = 400;
    throw error;
  }

  const razorpay = getRazorpay();

  // Create order in Razorpay
  const order = await razorpay.orders.create({
    amount: plan.amount,
    currency: plan.currency,
    receipt: `qmp3_${userId}_${Date.now()}`,
    notes: {
      userId: userId.toString(),
      plan: planKey,
    },
  });

  // Persist a "created" transaction record immediately
  await Transaction.create({
    userId,
    orderId: order.id,
    plan: planKey,
    amount: plan.amount,
    currency: plan.currency,
    status: 'created',
  });

  return {
    orderId: order.id,
    amount: plan.amount,
    currency: plan.currency,
    plan: planKey,
    planDetails: plan,
    keyId: config.razorpay.keyId,  // Send key to frontend for checkout
  };
};

/**
 * Verify a Razorpay payment signature and activate the user's plan
 * @param {string} userId
 * @param {object} paymentData - { razorpay_order_id, razorpay_payment_id, razorpay_signature }
 * @returns {Promise<{ success: boolean, user: object }>}
 */
export const verifyPayment = async (userId, { razorpay_order_id, razorpay_payment_id, razorpay_signature }) => {
  // 1. Verify signature
  const body = `${razorpay_order_id}|${razorpay_payment_id}`;
  const expectedSignature = crypto
    .createHmac('sha256', config.razorpay.keySecret)
    .update(body)
    .digest('hex');

  if (expectedSignature !== razorpay_signature) {
    const error = new Error('Payment verification failed — invalid signature');
    error.statusCode = 400;
    throw error;
  }

  // 2. Find the transaction
  const transaction = await Transaction.findOne({ orderId: razorpay_order_id });
  if (!transaction) {
    const error = new Error('Transaction not found');
    error.statusCode = 404;
    throw error;
  }

  // 3. Prevent duplicate processing
  if (transaction.status === 'paid') {
    const error = new Error('This payment has already been processed');
    error.statusCode = 409;
    throw error;
  }

  const plan = PLANS[transaction.plan];
  const now = new Date();
  const subscriptionEnd = new Date(now.getTime() + plan.validDays * 24 * 60 * 60 * 1000);

  // 4. Update transaction to "paid"
  transaction.paymentId = razorpay_payment_id;
  transaction.signature = razorpay_signature;
  transaction.status = 'paid';
  // invoiceNumber auto-generated by pre-save hook
  await transaction.save();

  // 5. Upgrade user plan + restore downloads
  const updatedUser = await User.findByIdAndUpdate(
    userId,
    {
      plan: transaction.plan,
      downloadsRemaining: plan.downloads,
      subscriptionStatus: 'active',
      subscriptionStart: now,
      subscriptionEnd,
    },
    { new: true }
  ).select('-password -refreshToken -resetPasswordToken -resetPasswordExpiry');

  return { success: true, user: updatedUser, transaction };
};

/**
 * Get a user's transaction history
 * @param {string} userId
 */
export const getUserTransactions = async (userId) => {
  return Transaction.find({ userId })
    .sort({ createdAt: -1 })
    .limit(50)
    .lean();
};

export default {
  PLANS,
  createOrder,
  verifyPayment,
  getUserTransactions,
};
